server:
  port: 9400

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9200/eureka/

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/user-market

  mail:
    host: smtp.gmail.com
    port: 587
    username: cefomarmadagascar@gmail.com
    password: rzuslfukhveigqqj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  auth:
    converter:
      resource-id: user-service
      principal-attribute: preferred_name
